"""test

Revision ID: b196a599b840
Revises: 83bb3bddd32c
Create Date: 2026-04-02 14:30:04.744506

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b196a599b840"
down_revision: Union[str, None] = "83bb3bddd32c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
